letter-frontend/package.json, letter-frontend/src/container/Login/Login.js, letter-frontend/src/container/Register/Register.js, letter-frontend/src/index.js, letter-frontend/src/store/actions/authActions.js, letter-frontend/src/store/reducers/authReducer.js, letter-frontend/src/store/reducers/rootReducer.js
add as per issue #5 
* redux
* redux thunk to be able to return functions in actions
* add actions for the register and login components
* add reducers for the register and login components
=> setup redux as per issue #5

letter-frontend/package-lock.json, letter-frontend/src/App.js, letter-frontend/src/container/Build/Build.js, letter-frontend/src/container/Build/ChampionFormBuild.js, letter-frontend/src/container/Build/CompFormBuild.js, letter-frontend/src/container/Build/ContentFormBuild.js, letter-frontend/src/container/Build/ItemsFormBuild.js, letter-frontend/src/container/Home/Home.js, letter-frontend/src/store/actions/buildsAction.js, letter-frontend/src/store/reducers/buildsReducer.js, letter-frontend/src/store/reducers/rootReducer.js
add to resolve issue #9 
* .toLowerCase() when filtering out the champion and items for search
* setup redux to create a build and get the builds
* displayed all the builds on the home page
=> add Redux to create a build and displayed the builds as per issue #9

letter-frontend/src/App.js, letter-frontend/src/component/NavBar/NavBar.js, letter-frontend/src/container/Build/Build.js, letter-frontend/src/container/DisplayBuild/DisplayBuild.js, letter-frontend/src/container/Home/Home.js, letter-frontend/src/container/Login/Login.js, letter-frontend/src/container/Register/Register.js, letter-frontend/src/index.js, letter-frontend/src/store/actions/authActions.js, letter-frontend/src/store/actions/buildsAction.js, letter-frontend/src/store/reducers/authReducer.js, letter-frontend/src/store/reducers/rootReducer.js
add as per issue #13 
* move navigational links to another component and exported it
* displayed certain links when user is not signed in and signed in
* route guarded links to create a build if the user isn't signed in
* route guarded register and login if the user is signed in
* connected the login and register component to firebase auth
* add rules to the firebase firestore for security
=> use firebase auth to login and register users as per issue #13

letter-frontend/.travis.yml
add a .travis file to setup the deployment with Travis CI
=> add travis CI to deploy to firebase

src/App.js, src/component/NavBar/NavBar.js, src/component/Settings/Settings.js, src/container/Settings/BuildSettings/BuildSettings.js, src/container/Settings/UserSettings/UserSettings.js
add
* a build settings container
*  a user settings container
* user settings component with a link to the build settings container and user settings container
* only displayed the link to the settings when the user is signed in
=> add settings component as per issue #21

src/container/Settings/UserSettings/UserSettings.js
add
* inputs for email, password and username
=> add form so a user can edit their account information as per issue #23

src/App.js, src/component/BuildList/BuildList.js, src/container/Build/ChampionFormBuild.js, src/container/Build/CompFormBuild.js, src/container/Build/ContentFormBuild.js, src/container/Build/ItemsFormBuild.js, src/container/Build/TitleFormBuild.js, src/container/Home/Home.js, src/container/Settings/BuildSettings/BuildSettings.js, src/container/Settings/BuildSettings/EditBuild/EditBuild.js, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #27 
* a BuildList component to display all the build in build settings and on the home page
* connect the form to firestore to update a build
* a action to update the build on firestore with the user inputted data
=> add edit build functionality as per issue #27

src/component/BuildList/BuildList.js, src/component/BuildList/BuildList.module.css, src/component/NavBar/NavBar.js, src/component/NavBar/NavBar.module.css, src/component/Settings/Settings.js, src/index.css
as per #30 
update:
* BuildList component jsx layout
* NavBar component links by removing the log out button
* Settings component links by adding the logout button
Add:
* BuildList component styles
* Navbar component styles
* container styles
=> add styles as per #30

src/App.js, src/component/BuildList/BuildList.js, src/container/DisplayBuild/DisplayBuild.js, src/container/Home/HomeNew.js, src/container/Home/SortOptions.js, src/container/Home/SortOptions.module.css, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #35 
* add two links to display the newest and most popular builds
* add a component to display the newest builds
* created upvoting system
* a user can upvote and remove the upvote to a build
=> add a upvoting system and sort by new and popular as per issue #35

src/container/Home/Home.js, src/container/Home/HomeNew.js
add 
* input to filter builds in the new and home pages
=> filter builds by champion name as per issue #36

src/container/DisplayBuild/DisplayBuild.js, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #39 
* action and reducer to create a doc in the comment collection
* displayed the comment below the build content
=> allow user to create comment on builds as per issue #39

.travis.yml, package.json
add as per issue #41 
* script to install required dependencies for the cloud functions
* configure travis to run this script
=> add a script for cloud function install as per issue #41

src/container/DisplayBuild/DisplayBuild.js, src/container/DisplayBuild/DisplayBuild.module.css, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #43 
* user can reply to comments
* see all the replies to a comment
=> implemented a reply system as per issue #43

src/container/DisplayBuild/DisplayBuild.js, src/container/Settings/BuildSettings/EditBuild/EditBuild.js, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #45 
* add a delete button for a build, comment, and reply
* add actions for deleting a build, comment, or reply 
* add reducers for deleting a build, comment, or reply
=> add functionality to allow user to delete their content as per issue #45

src/container/DisplayBuild/DisplayBuild.js, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #46 
* action to update a comment or reply
* reducer to update a comment or reply
* dry up the code to use the same text box to reply to edit a comment or reply and to reply to a comment
=> add functionality to edit a comment or reply

src/App.js, src/container/Settings/UserSettings/UserSettings.js, src/container/Settings/UserSettings/UserSettingsForms/DeleteUserAccount.js, src/container/Settings/UserSettings/UserSettingsForms/UpdateUserEmail.js, src/store/actions/authActions.js, src/store/reducers/authReducer.js
add as per issue #50 
* delete the user information that includes builds they liked, comments, replies and builds they created
* created an action and reducer to delete a user account
=> add functionality to delete a user account as per issue #50

src/container/DisplayBuild/DisplayBuild.js
as per #54
add:
* ReactQuill functionality
update:
* replace textarea with ReactQuill
* handleShowReplyForm, handleShowEditCommentForm, handleShowEditReplyForm, and showTextArea functions to fix display bug with the reply/edit text box
=> replace textarea with ReactQuill as per #54

src/component/NavBar/NavBar.js, src/container/DisplayBuild/DisplayBuild.js, src/container/DisplayBuild/DisplayBuild.module.css, src/index.css
as per #56 
add:
* styles to DisplayBuild container
update:
* DisplayBuild container comment control order
* NavBar component link order
=> add styles to DisplayBuild container as per #56

public/index.html, src/container/DisplayBuild/DisplayBuild.js, src/container/DisplayBuild/DisplayBuild.module.css, src/index.css
add as per issue #58 
* roboto font to all text
update as per issue #58 
* the layout and css on the comments, replies, and build about the user
=> polish css and add roboto font to polish it as per issue #58

src/component/NavBar/NavBar.module.css, src/container/Home/Home.js, src/container/Home/HomeNew.js, src/container/Home/SortOptions.module.css
add styling to the input that filters builds on the pages that display builds as per issue #60
=> update styling for filter as per issue #60

src/container/Login/Login.js, src/container/Login/Login.module.css, src/container/Register/Register.js, src/container/Register/Register.module.css
as per #62 
add: 
* Styles to Login container
* Styles to Register container
=> add styles to Login and Register containers as per #62

src/container/Build/Build.js, src/container/Build/Build.module.css, src/container/Build/ChampionFormBuild.js, src/container/Build/CompFormBuild.js, src/container/Build/ContentFormBuild.js, src/container/Build/ItemsFormBuild.js, src/container/Build/TitleFormBuild.js, src/container/Register/Register.module.css
add as per issue #64
* sub text to explain the inputs
* styles for the form to create a build
=> add css to create a build page as per issue #64

src/container/Build/CompFormBuild.js, src/container/Build/ItemsFormBuild.js
add as per issue #66
* reset the champion and items select when adding a new item
* reset the input
=> adding a champion or item removes it from the input as per issue #66

src/container/Build/Build.module.css, src/container/Build/CompFormBuild.js
add as per issue #68 
* on smaller screen stack the champion icons when 4 are selected
* on bigger screen stack the champion icons when it reaches the end of the page
=> selecting multiple champions collapse the divs of each other as per issue #68

src/container/DisplayBuild/DisplayBuild.js, src/container/DisplayBuild/DisplayBuild.module.css
add as per issue #70 
* margin bottom to the login prompt and the text box to create a comment to give it some space when there isn't any comments
* check if the comment buildId matches with the id of the URL
=> remove comment leak and add margin #70

src/container/Build/Build.module.css, src/container/Settings/BuildSettings/BuildSettings.js, src/container/Settings/BuildSettings/BuildSettings.module.css, src/container/Settings/BuildSettings/EditBuild/EditBuild.js, src/container/Settings/BuildSettings/EditBuild/EditBuild.module.css
add as per issue #72 
* css for the form to edit a build
* titles for editing a build and seeing all your builds
=> update the styles for editng a build and displaying all builds

src/component/Settings/Settings.js, src/component/Settings/Settings.module.css, src/container/Settings/UserSettings/UserSettings.js, src/container/Settings/UserSettings/UserSettings.module.css
update as per issue #74 
* update layout of the links linking to different settings
=> update css for user settings and settings page #74

src/container/Settings/UserSettings/UserSettingsForms/DeleteUserAccount.js, src/container/Settings/UserSettings/UserSettingsForms/UpdateUserEmail.js, src/container/Settings/UserSettings/UserSettingsForms/UpdateUserPassword.js, src/container/Settings/UserSettings/UserSettingsForms/UpdateUserUsername.js, src/container/Settings/UserSettings/UserSettingsForms/UserSettingsForm.module.css
update as per issue #76 
* the layout of the page with css to match the design
=> update styles for individual forms issue #76

src/container/Settings/UserSettings/Reauthenticate.js, src/container/Settings/UserSettings/UserSettingsForms/UserSettingsForm.module.css
add as per issue #78 
* classes to the form inputs and container
=> add styles to reauthenticate page

src/container/Register/Register.js
add as per issue #79 
* replace spaces with underscore for username
* trim spaces of the values of inputs
=> trim the values of inputs and restricted username as per issue #79

functions/index.js, src/component/BuildList/BuildList.js, src/component/NavBar/NavBar.js, src/store/actions/authActions.js, src/store/actions/buildsAction.js, src/store/reducers/authReducer.js
remove all console logs that are not necessary
=> remove all console logs that are not needed

public/manifest.json, src/index.js
update start url and move service worker registration outside the firebase on ready function
=> update start url and move where service worker registered #86

src/component/NavBar/NavBar.js
update navigation link text from build to create as per issue #91
=> update navigation link text

src/container/DisplayBuild/DisplayBuild.js, src/store/actions/buildsAction.js, src/store/reducers/buildsReducer.js
add as per issue #93 
* fix the logic displaying the upvote and downvote button
* add redux functionality for downvoting a build
=> add redux functionality and fix upvote button #93

public/index.html
installed google analytics as per issue #95
=> installed google analytics as per issue #95
